services:
  sport-hub-api:
    image: "sport-hub-api"
    build:
      context: .
    container_name: sport-hub-api
    ports:
      - "3011:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sport-hub-net
    volumes:
      - "./Upload:/upload"
  sport-hub-db:
    image: postgres:latest
    container_name: sport_hub
    ports:
      - "3012:5432" # Map the application port
    environment:
      - POSTGRES_DB=sport_hub
      - POSTGRES_PASSWORD=sporthub@1234
      - POSTGRES_USER=sportHub
    volumes:
      - sportHub-pg-vol:/var/lib/postgresql/data
    networks:
      - sport-hub-net
volumes:
  sportHub-pg-vol:
networks:
  sport-hub-net: