spring:
  application:
    name: sportHub
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://136.228.158.126:3012/sport_hub
    username: sportHub
    password: sporthub@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #handle file size
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
#file-upload:
#  server-path: D://TosTrip//images-upload
#  base-uri: http://localhost:8080/upload/
file-upload:
  server-path: /Users/eunglyzhia/Documents/backend/studentAPI/images/
  base-uri: http://localhost:8080/images/
